export const CITY_NAMES = [
  "VANCOUVER",
  "MONTREAL",
  "TORONTO",
  "BURNABY",
  "LANGLEY",
  "SURREY",
  "RICHMOND",
  "WHISTLER",
  "MISSISSAUGA",
  "CALGARY",
  "SQUAMISH",
  "OTTAWA",
  "DORVAL",
  "VICTORIA",
  "COQUITLAM",
  "WEST VANCOUVER",
];

export const CATEGORIES = [
  "Evo",
  "DoorDash",
  "Restaurants",    
  "Bills",
  "Groceries",
  "Online Subscriptions",
  "Rogers",
  "Clothes",
  "Personal",
  "Entertainment",
  "Online Shopping",
  "Transport",
];
